name: snote
description: "A 'Simple' note taking app"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  # Dependency Injection
  get_it: ^7.7.0
  # Sqflite, local database
  sqflite: ^2.3.3+1
  # Http, remote database
  http: ^1.2.1
  # Path to store locally the data
  path: ^1.9.0
  path_provider: ^2.1.3
  # Icon
  flutter_launcher_icons: ^0.13.1
  # Google fonts
  google_fonts: ^6.2.1
  # Other
  lottie: ^3.1.0
  equatable: ^2.0.5
  # Bottom nav bar
  google_nav_bar: ^5.0.6
  # Svg icons
  flutter_svg: ^2.0.10+1
  # Date Formator
  intl: ^0.19.0
  json_annotation: ^4.9.0
  # Dot env
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/app_icon/
    - .env

# APP ICON
flutter_icons:
  image_path: assets/app_icon/Snote_logo.png
  android: "launcher_icon"
  ios: "AppIcon"
  remove_alpha_ios: true
  min_sdk_ios: 21
